NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app:
    resource: '@AppBundle/Controller/'
    type: annotation

provider:
    resource: "@ProviderBundle/Resources/config/routing.yml"
    prefix:   /provider

customer:
    resource: "@CustomerBundle/Resources/config/routing.yml"
    prefix:   /customer

business:
    resource: "@BusinessBundle/Resources/config/routing.yml"
    prefix:   /business

store:
    resource: "@StoreBundle/Resources/config/routing.yml"
    prefix:   /store

product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /product