# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        entity:
            entity:
                class: AppBundle:User
                property: username

        token:
            entity:
                class: AppBundle:Token
                property: token

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        provider:
            pattern: ^/provider/(?!(register|login|logout))
            guard:
                authenticators:
                    - app.provider_token_authenticator
            provider: token

        customer:
            pattern: ^/customer/(?!(register|login|logout))
            guard:
                authenticators:
                    - app.customer_token_authenticator
            provider: token

        business:
            pattern: ^/business
            guard:
                authenticators:
                    - app.provider_token_authenticator
            provider: token

        store:
            pattern: ^/store
            guard:
                authenticators:
                    - app.provider_token_authenticator
            provider: token

        product:
            pattern: ^/product
            guard:
                authenticators:
                    - app.provider_token_authenticator
            provider: token

        main:
            anonymous: ~

    encoders:
        AppBundle\Entity\User: bcrypt
